import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on Oct 6, 2020, 4:11:03 PM
 */

/**
 *
 * @author Microsoft
 */

public class Home extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    DefaultTableModel tm = null;
    String ClubName = null;
    ResultSet rs = null;
    /** Creates new form Home */
    public Home() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentLoginFrame = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RollNo = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        AuthorityLoginFrame = new javax.swing.JFrame();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        PF1 = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        StudentDashboard = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        NewsFrame = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        EventsFrame = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        MessMenuFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        ClubLoginFrame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clubname = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ClubDashboard = new javax.swing.JFrame();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addEventFrame = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        eventDate = new javax.swing.JTextField();
        eventTime = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        deleteEventFrame = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        AuthorityDashboard = new javax.swing.JFrame();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        addMenuFrame = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        messName = new javax.swing.JTextField();
        dishName = new javax.swing.JTextField();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        addNewsFrame = new javax.swing.JFrame();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        news = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        MapFrame = new javax.swing.JFrame();
        jButton36 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        StudentLoginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        StudentLoginFrame.setMinimumSize(new java.awt.Dimension(325, 460));
        StudentLoginFrame.getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        StudentLoginFrame.getContentPane().add(jButton3);
        jButton3.setBounds(40, 310, 90, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 18));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        StudentLoginFrame.getContentPane().add(jButton4);
        jButton4.setBounds(190, 310, 80, 30);
        StudentLoginFrame.getContentPane().add(RollNo);
        RollNo.setBounds(140, 120, 140, 20);
        StudentLoginFrame.getContentPane().add(pwd);
        pwd.setBounds(140, 190, 140, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText("Roll No. :");
        StudentLoginFrame.getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 120, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel2.setText("Password :");
        StudentLoginFrame.getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 190, 98, 22);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel23.setText("Student Login");
        StudentLoginFrame.getContentPane().add(jLabel23);
        jLabel23.setBounds(100, 30, 130, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel22.setText("jLabel22");
        StudentLoginFrame.getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 310, 420);

        AuthorityLoginFrame.setMinimumSize(new java.awt.Dimension(325, 460));
        AuthorityLoginFrame.getContentPane().setLayout(null);

        jButton25.setFont(new java.awt.Font("Arial", 1, 18));
        jButton25.setText("Login");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        AuthorityLoginFrame.getContentPane().add(jButton25);
        jButton25.setBounds(51, 289, 100, 31);

        jButton26.setFont(new java.awt.Font("Arial", 1, 18));
        jButton26.setText("Back");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        AuthorityLoginFrame.getContentPane().add(jButton26);
        jButton26.setBounds(190, 290, 90, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel14.setText("User Name :");
        AuthorityLoginFrame.getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 130, 120, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel15.setText("Password :");
        AuthorityLoginFrame.getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 200, 100, 20);
        AuthorityLoginFrame.getContentPane().add(userName);
        userName.setBounds(160, 140, 100, 20);
        AuthorityLoginFrame.getContentPane().add(PF1);
        PF1.setBounds(160, 200, 100, 20);

        jLabel24.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel24.setText("jLabel24");
        AuthorityLoginFrame.getContentPane().add(jLabel24);
        jLabel24.setBounds(0, -160, 320, 590);

        StudentDashboard.setMinimumSize(new java.awt.Dimension(310, 440));
        StudentDashboard.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16));
        jLabel3.setText("WELCOME TO THE VIRTUAL GUIDE");
        StudentDashboard.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 290, 40);

        jButton5.setFont(new java.awt.Font("Arial", 1, 14));
        jButton5.setText("News");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        StudentDashboard.getContentPane().add(jButton5);
        jButton5.setBounds(40, 130, 90, 30);

        jButton6.setFont(new java.awt.Font("Arial", 1, 14));
        jButton6.setText("Events");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        StudentDashboard.getContentPane().add(jButton6);
        jButton6.setBounds(170, 130, 90, 30);

        jButton7.setFont(new java.awt.Font("Arial", 1, 14));
        jButton7.setText("Mess Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        StudentDashboard.getContentPane().add(jButton7);
        jButton7.setBounds(20, 210, 120, 30);

        jButton8.setFont(new java.awt.Font("Arial", 1, 14));
        jButton8.setText("Nitk Map");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        StudentDashboard.getContentPane().add(jButton8);
        jButton8.setBounds(170, 210, 100, 30);

        jButton14.setFont(new java.awt.Font("Arial", 1, 14));
        jButton14.setText("Sign Out");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        StudentDashboard.getContentPane().add(jButton14);
        jButton14.setBounds(100, 290, 100, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel25.setText("jLabel25");
        StudentDashboard.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, -250, 300, 650);

        NewsFrame.setMinimumSize(new java.awt.Dimension(315, 450));
        NewsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                NewsFrameWindowActivated(evt);
            }
        });
        NewsFrame.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel6.setText("News Section");
        NewsFrame.getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 80, 130, 20);

        jButton11.setFont(new java.awt.Font("Arial", 1, 14));
        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        NewsFrame.getContentPane().add(jButton11);
        jButton11.setBounds(110, 290, 70, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "News", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        NewsFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 280, 110);

        jLabel26.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel26.setText("jLabel26");
        NewsFrame.getContentPane().add(jLabel26);
        jLabel26.setBounds(0, -160, 300, 580);

        EventsFrame.setMinimumSize(new java.awt.Dimension(325, 450));
        EventsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                EventsFrameWindowActivated(evt);
            }
        });
        EventsFrame.getContentPane().setLayout(null);

        jTable2.setFont(new java.awt.Font("Arial", 1, 12));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Club", "Event Name", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        EventsFrame.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 300, 160);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText("Club :");
        EventsFrame.getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 20, 40, 20);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 12));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EventsFrame.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(130, 20, 80, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 14));
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        EventsFrame.getContentPane().add(jButton10);
        jButton10.setBounds(110, 70, 90, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 14));
        jButton12.setText("Back to Dashboard");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        EventsFrame.getContentPane().add(jButton12);
        jButton12.setBounds(65, 330, 180, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel27.setText("jLabel27");
        EventsFrame.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 320, 410);

        MessMenuFrame.setMinimumSize(new java.awt.Dimension(305, 450));
        MessMenuFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                MessMenuFrameWindowActivated(evt);
            }
        });
        MessMenuFrame.getContentPane().setLayout(null);

        jTable3.setFont(new java.awt.Font("Arial", 1, 12));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Dish Name"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        MessMenuFrame.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 140, 250, 110);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setText("Select Mess :");
        MessMenuFrame.getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 40, 94, 17);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mess 1", "Mess 2", "Mess 3" }));
        MessMenuFrame.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 40, 80, 20);

        jButton9.setFont(new java.awt.Font("Arial", 1, 14));
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        MessMenuFrame.getContentPane().add(jButton9);
        jButton9.setBounds(100, 85, 90, 30);

        jButton13.setFont(new java.awt.Font("Arial", 1, 14));
        jButton13.setText("Back to Dashboard");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        MessMenuFrame.getContentPane().add(jButton13);
        jButton13.setBounds(60, 300, 180, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel28.setText("jLabel28");
        MessMenuFrame.getContentPane().add(jLabel28);
        jLabel28.setBounds(0, -120, 290, 530);

        ClubLoginFrame.setMinimumSize(new java.awt.Dimension(305, 460));
        ClubLoginFrame.getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Club Name :");
        ClubLoginFrame.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 150, 83, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setText("Password :");
        ClubLoginFrame.getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 200, 76, 17);
        ClubLoginFrame.getContentPane().add(clubname);
        clubname.setBounds(130, 150, 110, 20);
        ClubLoginFrame.getContentPane().add(pass);
        pass.setBounds(130, 200, 110, 20);

        jButton16.setFont(new java.awt.Font("Arial", 1, 14));
        jButton16.setText("Login");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        ClubLoginFrame.getContentPane().add(jButton16);
        jButton16.setBounds(60, 290, 80, 30);

        jButton17.setFont(new java.awt.Font("Arial", 1, 14));
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        ClubLoginFrame.getContentPane().add(jButton17);
        jButton17.setBounds(170, 290, 80, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel30.setText("Club Login");
        ClubLoginFrame.getContentPane().add(jLabel30);
        jLabel30.setBounds(100, 60, 100, 30);

        jLabel29.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel29.setText("jLabel29");
        ClubLoginFrame.getContentPane().add(jLabel29);
        jLabel29.setBounds(0, -180, 290, 600);

        ClubDashboard.setMinimumSize(new java.awt.Dimension(305, 460));
        ClubDashboard.getContentPane().setLayout(null);

        jButton18.setFont(new java.awt.Font("Arial", 1, 14));
        jButton18.setText("Add an Event");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        ClubDashboard.getContentPane().add(jButton18);
        jButton18.setBounds(10, 140, 130, 40);

        jButton19.setFont(new java.awt.Font("Arial", 1, 14));
        jButton19.setText("Delete a Event");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        ClubDashboard.getContentPane().add(jButton19);
        jButton19.setBounds(120, 220, 150, 40);

        jButton24.setFont(new java.awt.Font("Arial", 1, 14));
        jButton24.setText("Sign Out");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        ClubDashboard.getContentPane().add(jButton24);
        jButton24.setBounds(20, 300, 100, 40);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel32.setText("Dashboard");
        ClubDashboard.getContentPane().add(jLabel32);
        jLabel32.setBounds(100, 50, 100, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel31.setText("jLabel31");
        ClubDashboard.getContentPane().add(jLabel31);
        jLabel31.setBounds(0, -140, 290, 560);

        addEventFrame.setMinimumSize(new java.awt.Dimension(315, 460));
        addEventFrame.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setText("Tell us Something about the Event");
        addEventFrame.getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 40, 260, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel10.setText("Name of the Event :");
        addEventFrame.getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 130, 140, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel11.setText("Date :");
        addEventFrame.getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 180, 40, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel12.setText("Time :");
        addEventFrame.getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 240, 41, 17);
        addEventFrame.getContentPane().add(eventName);
        eventName.setBounds(160, 130, 90, 20);
        addEventFrame.getContentPane().add(eventDate);
        eventDate.setBounds(160, 180, 90, 20);
        addEventFrame.getContentPane().add(eventTime);
        eventTime.setBounds(160, 240, 90, 20);

        jButton20.setFont(new java.awt.Font("Arial", 1, 14));
        jButton20.setText("Add Event");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        addEventFrame.getContentPane().add(jButton20);
        jButton20.setBounds(30, 300, 110, 30);

        jButton21.setFont(new java.awt.Font("Arial", 1, 14));
        jButton21.setText("Back");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        addEventFrame.getContentPane().add(jButton21);
        jButton21.setBounds(180, 300, 80, 30);

        jLabel33.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel33.setText("jLabel33");
        addEventFrame.getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 300, 420);

        deleteEventFrame.setMinimumSize(new java.awt.Dimension(290, 440));
        deleteEventFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                deleteEventFrameWindowActivated(evt);
            }
        });
        deleteEventFrame.getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel13.setText("Select the Event Name :");
        deleteEventFrame.getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 87, 167, 20);

        jButton22.setFont(new java.awt.Font("Arial", 1, 14));
        jButton22.setText("Cancel Event");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        deleteEventFrame.getContentPane().add(jButton22);
        jButton22.setBounds(70, 230, 130, 40);

        jButton23.setFont(new java.awt.Font("Arial", 1, 14));
        jButton23.setText("Back");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        deleteEventFrame.getContentPane().add(jButton23);
        jButton23.setBounds(100, 300, 70, 40);

        jComboBox3.setFont(new java.awt.Font("Arial", 1, 12));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        deleteEventFrame.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(100, 120, 80, 30);

        jLabel34.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel34.setText("jLabel34");
        deleteEventFrame.getContentPane().add(jLabel34);
        jLabel34.setBounds(0, -150, 280, 570);

        AuthorityDashboard.setMinimumSize(new java.awt.Dimension(280, 460));
        AuthorityDashboard.getContentPane().setLayout(null);

        jButton27.setFont(new java.awt.Font("Arial", 1, 14));
        jButton27.setText("Add to Mess Menu");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        AuthorityDashboard.getContentPane().add(jButton27);
        jButton27.setBounds(50, 240, 170, 40);

        jButton28.setFont(new java.awt.Font("Arial", 1, 14));
        jButton28.setText("Add News");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        AuthorityDashboard.getContentPane().add(jButton28);
        jButton28.setBounds(80, 150, 110, 30);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel36.setText("Dashboard");
        AuthorityDashboard.getContentPane().add(jLabel36);
        jLabel36.setBounds(70, 60, 140, 40);

        jButton34.setFont(new java.awt.Font("Arial", 1, 18));
        jButton34.setText("Sign Out");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        AuthorityDashboard.getContentPane().add(jButton34);
        jButton34.setBounds(80, 350, 110, 40);

        jLabel35.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel35.setText("jLabel35");
        AuthorityDashboard.getContentPane().add(jLabel35);
        jLabel35.setBounds(0, -100, 270, 520);

        addMenuFrame.setMinimumSize(new java.awt.Dimension(305, 460));
        addMenuFrame.getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel16.setText("Mess :");
        addMenuFrame.getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 140, 50, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel17.setText("Dish :");
        addMenuFrame.getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 180, 40, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel18.setText("Day :");
        addMenuFrame.getContentPane().add(jLabel18);
        jLabel18.setBounds(70, 220, 40, 17);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        addMenuFrame.getContentPane().add(jComboBox4);
        jComboBox4.setBounds(120, 220, 40, 20);

        messName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messNameActionPerformed(evt);
            }
        });
        addMenuFrame.getContentPane().add(messName);
        messName.setBounds(120, 140, 90, 20);
        addMenuFrame.getContentPane().add(dishName);
        dishName.setBounds(120, 180, 90, 20);

        jButton30.setFont(new java.awt.Font("Arial", 1, 14));
        jButton30.setText("Add Dish");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        addMenuFrame.getContentPane().add(jButton30);
        jButton30.setBounds(40, 300, 100, 30);

        jButton31.setFont(new java.awt.Font("Arial", 1, 14));
        jButton31.setText("Back");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        addMenuFrame.getContentPane().add(jButton31);
        jButton31.setBounds(170, 300, 80, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel19.setText("Update Mess Menu");
        addMenuFrame.getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 50, 170, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel37.setText("jLabel37");
        addMenuFrame.getContentPane().add(jLabel37);
        jLabel37.setBounds(0, -160, 290, 580);

        addNewsFrame.setMinimumSize(new java.awt.Dimension(305, 460));
        addNewsFrame.getContentPane().setLayout(null);

        jButton32.setFont(new java.awt.Font("Arial", 1, 14));
        jButton32.setText("Add News");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        addNewsFrame.getContentPane().add(jButton32);
        jButton32.setBounds(40, 270, 110, 30);

        jButton33.setFont(new java.awt.Font("Arial", 1, 14));
        jButton33.setText("Back");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        addNewsFrame.getContentPane().add(jButton33);
        jButton33.setBounds(180, 270, 80, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel20.setText("Update News");
        addNewsFrame.getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 60, 160, 40);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setText("News :");
        addNewsFrame.getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 170, 46, 17);
        addNewsFrame.getContentPane().add(news);
        news.setBounds(80, 170, 180, 20);

        jLabel38.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel38.setText("jLabel38");
        addNewsFrame.getContentPane().add(jLabel38);
        jLabel38.setBounds(0, -180, 300, 610);

        MapFrame.setMinimumSize(new java.awt.Dimension(350, 550));
        MapFrame.getContentPane().setLayout(null);

        jButton36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton36.setText("Back");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        MapFrame.getContentPane().add(jButton36);
        jButton36.setBounds(160, 480, 80, 30);

        jLabel39.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\NITK MAP 5.jpg")); // NOI18N
        jLabel39.setText("jLabel39");
        MapFrame.getContentPane().add(jLabel39);
        jLabel39.setBounds(-30, -160, 380, 840);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(325, 460));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18));
        jButton1.setText("Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 220, 120, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18));
        jButton2.setText("College Management");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 300, 230, 50);

        jButton15.setFont(new java.awt.Font("Arial", 1, 18));
        jButton15.setText("Club");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(100, 150, 100, 40);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel40.setForeground(new java.awt.Color(0, 0, 255));
        jLabel40.setText("NITK VIRTUAL GUIDE");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(30, 50, 260, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon("D:\\saish\\NitkVirtualGuide\\src\\background_1.jpg")); // NOI18N
        jLabel41.setText("jLabel41");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(0, -60, 320, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String roll = RollNo.getText();
        String pass = new String(pwd.getPassword());
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT Password FROM Student WHERE RollNo = '" + roll + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass1 = rs.getString(1);
            if(pass.equals(pass1)){
                RollNo.setText("");
                pwd.setText("");
                StudentLoginFrame.dispose();
                StudentDashboard.setVisible(true);
            }
            else{
                RollNo.setText("");
                pwd.setText("");
                JOptionPane.showMessageDialog(null, "Invalid Roll No. or password. Try again!");
            }
     }
    catch(Exception e){
        RollNo.setText("");
        pwd.setText("");
        JOptionPane.showMessageDialog(null, "Invalid Roll No. or password. Try again!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        StudentLoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AuthorityLoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        StudentLoginFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        StudentDashboard.dispose();
        NewsFrame.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        StudentDashboard.dispose();
        MessMenuFrame.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        StudentDashboard.dispose();
        EventsFrame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //day = DAYOFWEEK(CURDATE());
        DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
        tm.setRowCount(0);
        String mess = (String)jComboBox1.getSelectedItem();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = null;
            if(mess.equals("--Select Mess--")){
                sql = "SELECT * FROM Mess where Day = DAYOFWEEK(curdate());";
            }
            else{
                sql = "SELECT * FROM Mess WHERE  Day = DAYOFWEEK(curdate()) and Name='"+mess+"';";
            }
            rs = stmt.executeQuery(sql);
            while(rs.next()){
               tm.addRow(new Object [] {rs.getString("Dish")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void MessMenuFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MessMenuFrameWindowActivated
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
        tm.setRowCount(0);
        jComboBox1.removeAllItems();
        jComboBox1.addItem("--Select Mess--");
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT DISTINCT Name FROM Mess ORDER BY Name ASC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                jComboBox1.addItem(rs.getString("Name"));
            }
            jComboBox1.setSelectedItem("--Select Mess--");
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_MessMenuFrameWindowActivated

    private void EventsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EventsFrameWindowActivated
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
        tm.setRowCount(0);
        jComboBox2.removeAllItems();
        jComboBox2.addItem("--Select Club--");
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT DISTINCT Club FROM Event ORDER BY Club ASC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                jComboBox2.addItem(rs.getString("Club"));
            }
            jComboBox1.setSelectedItem("--Select Club--");
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_EventsFrameWindowActivated

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
        tm.setRowCount(0);
        String club = (String)jComboBox2.getSelectedItem();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = null;
            if(club.equals("--Select Club--")){
                sql = "SELECT * FROM Event where Date>=curdate();";
            }
            else{
                sql = "SELECT * FROM Event WHERE Club = '"+club+"' and Date>=curdate();";
            }
            rs = stmt.executeQuery(sql);
            while(rs.next()){
               tm.addRow(new Object [] {rs.getString("Club"),rs.getString("Name"),rs.getString("Date"),rs.getString("Time")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void NewsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_NewsFrameWindowActivated
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) jTable1.getModel();
        tm1.setRowCount(0);
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = null;
            sql = "SELECT * FROM News WHERE Date>=curdate();";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
               tm1.addRow(new Object [] {rs.getString("News"),rs.getString("Date")});
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_NewsFrameWindowActivated

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        NewsFrame.dispose();
        StudentDashboard.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        EventsFrame.dispose();
        StudentDashboard.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        MessMenuFrame.dispose();
        StudentDashboard.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        StudentDashboard.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        ClubName = clubname.getText();
        String pwd = new String(pass.getPassword());
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT Password FROM Clubs WHERE Club = '" + ClubName + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass1 = rs.getString(1);
            if(pwd.equals(pass1)){
                clubname.setText("");
                pass.setText("");
                ClubLoginFrame.dispose();
                ClubDashboard.setVisible(true);
            }
            else{
                clubname.setText("");
                pass.setText("");
                JOptionPane.showMessageDialog(null, "Invalid Name or password. Try again!");
            }
     }
    catch(Exception e){
        clubname.setText("");
        pass.setText("");
        JOptionPane.showMessageDialog(null, "Invalid Name or password. Try again!");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        ClubLoginFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        ClubDashboard.dispose();
        addEventFrame.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        ClubDashboard.dispose();
        deleteEventFrame.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        String name = eventName.getText();
        String date = eventDate.getText();
        String time = eventTime.getText();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "INSERT INTO Event VALUES('" + ClubName + "', '" +  name + "', '" + date + "', '" + time + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Event added successfully!");
            eventName.setText("");
            eventDate.setText("");
            eventTime.setText("");
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        addEventFrame.dispose();
        ClubDashboard.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void deleteEventFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_deleteEventFrameWindowActivated
        // TODO add your handling code here:
        jComboBox3.removeAllItems();
        jComboBox3.addItem("--Select Event--");
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT DISTINCT Name FROM Event where Club='"+ClubName+"' ORDER BY Name ASC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                jComboBox3.addItem(rs.getString("Name"));
            }
            jComboBox3.setSelectedItem("--Select Event--");
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_deleteEventFrameWindowActivated

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        String name = (String)jComboBox3.getSelectedItem();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql=null;
            if(name.equals("--Select Event--"))
            {
                sql=null;
                JOptionPane.showMessageDialog(null, "Please select a Event");
            }
            else{
                sql = "delete from Event where Club ='" + ClubName + "' and Name ='" +  name + "';";
                System.out.println(sql);
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "Event canceled successfully!");
            }
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ClubLoginFrame.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        deleteEventFrame.dispose();
        ClubDashboard.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        ClubDashboard.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        AuthorityLoginFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        AuthorityDashboard.dispose();
        addMenuFrame.setVisible(true);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        AuthorityDashboard.dispose();
        addNewsFrame.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        String mess = messName.getText();
        String dish = dishName.getText();
        String day = (String)jComboBox4.getSelectedItem();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "INSERT INTO Mess VALUES('" + mess + "', '" +  dish + "', '" + day + "';";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Dish added successfully!");
            messName.setText("");
            dishName.setText("");
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        addMenuFrame.dispose();
        AuthorityDashboard.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        String News = news.getText();
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "INSERT INTO News VALUES('" + News + "', curdate());";
            System.out.println(sql);
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "News Updated successfully!");
            news.setText("");
            stmt.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        String Name = userName.getText();
        String pass = new String(PF1.getPassword());
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            stmt = con.createStatement();
            String sql = "SELECT Password FROM Authority WHERE UserName = '" + Name + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            String pass1 = rs.getString(1);
            if(pass.equals(pass1)){
                AuthorityLoginFrame.dispose();
                AuthorityDashboard.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Roll No. or password. Try again!");
            }
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Roll No. or password. Try again!");
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        addNewsFrame.dispose();
        AuthorityDashboard.setVisible(true);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void messNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messNameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        StudentDashboard.dispose();
        MapFrame.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
        MapFrame.dispose();
        StudentDashboard.setVisible(true);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        AuthorityDashboard.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton34ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AuthorityDashboard;
    private javax.swing.JFrame AuthorityLoginFrame;
    private javax.swing.JFrame ClubDashboard;
    private javax.swing.JFrame ClubLoginFrame;
    private javax.swing.JFrame EventsFrame;
    private javax.swing.JFrame MapFrame;
    private javax.swing.JFrame MessMenuFrame;
    private javax.swing.JFrame NewsFrame;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JTextField RollNo;
    private javax.swing.JFrame StudentDashboard;
    private javax.swing.JFrame StudentLoginFrame;
    private javax.swing.JFrame addEventFrame;
    private javax.swing.JFrame addMenuFrame;
    private javax.swing.JFrame addNewsFrame;
    private javax.swing.JTextField clubname;
    private javax.swing.JFrame deleteEventFrame;
    private javax.swing.JTextField dishName;
    private javax.swing.JTextField eventDate;
    private javax.swing.JTextField eventName;
    private javax.swing.JTextField eventTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField messName;
    private javax.swing.JTextField news;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

}
